version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sitecount-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ywfuvf4084n2"
s3_prefix = "sitecount-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
